name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:	
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Build Storybook
            run: |
              npm install
              npm run build-storybook

          - name: Deploy
            uses: impurity-dev/github-pages-deploy-action@releases/v3
            with:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              BRANCH: gh-pages
              FOLDER: dist-storybook